version: "3.9"
services:
  bot:
    image: mrdavidoneill/whendidtherocketlaunch_bot:latest
    command: "python ./main.py"
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 8666
